# Generated by Django 2.2.9 on 2020-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_made',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creantion date and time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.CharField(default='#', help_text='Ex: 20:00', max_length=5, verbose_name='Reservation time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='observations',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.CharField(default='#', help_text='Ex: 30', max_length=3, verbose_name='Table for?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(default='#', help_text='Ex: 01/01/2020', max_length=10, verbose_name='Reservation date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='#', max_length=20, verbose_name='Name'),
        ),
    ]
